import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.js';
import {createApp} from '../src/server.js';
import {streamLink,publicStreams} from '../src/streams.js';
import {checkTwitchStreams} from '../src/stream-monitor.js';
import {streamCandidates,distinctSlots,playerUrl} from '../public/watch.js';
import {ChatResponder} from '../src/chat.js';
const profile={map:'der-eisendrache',category:'No Gums'};
test('session groups map/categories, counts observed resets, and excludes missing/practice times',t=>{
  let now=1700000000000;const store=new Store(':memory:',()=>now);t.after(()=>store.close());
  const {player}=store.register('Runner');
  const send=(attemptId,changes={})=>store.ingest(player.id,{attemptId,sequence:1,profile,phase:'Running',index:1,elapsedMs:300000,current:'crackle',splits:[{index:0,name:'bow',ms:200000}],complete:true,observedAt:now,...changes});
  send('attempt-first');now+=1000;send('idle-reset-1',{phase:'NotRunning',index:-1,elapsedMs:0,current:null,splits:[],complete:false});
  now+=1000;send('attempt-second',{phase:'Ended',elapsedMs:280000,splits:[{index:0,name:'bow',ms:280000}],current:null});
  send('idle-reset-2',{phase:'NotRunning',index:-1,elapsedMs:0,splits:[],current:null});
  send('attempt-practice',{practice:true,splits:[{index:0,name:'bow',ms:1000}]});
  send('attempt-mega',{profile:{...profile,category:'Mega Gums'}});
  send('attempt-moon',{profile:{map:'moon',category:'Any%'},splits:[],index:0});
  const p=store.get('players',player.id),s=store.sessionStats(p),g=s.groups.find(g=>g.profile.category==='No Gums');
  assert.equal(s.attempts,5);assert.equal(s.resets,1);assert.equal(s.durationMs,2000);assert.equal(s.groups.length,3);
  assert.equal(g.fastestMs,280000);assert.equal(g.splits[0].averageMs,240000);assert.equal(g.splits[0].bestMs,200000);assert.equal(g.splits[0].count,2);
  assert.equal(s.current.map,'moon');assert.equal(s.unconfirmedEnds,2);
  assert.match(store.answer('!session @Runner'),/average 4:00/);
  const reply=new ChatResponder(store,190,()=>now).respond('chat','viewer','1','!session @Runner');
  assert.match(reply,/1 resets/);assert.match(reply,/https:\/\/doctormonty.beer/);assert.ok(reply.length<=190);
  now+=31000;store.session(store.get('players',player.id),'end');const ended=store.sessionStats(store.get('players',player.id));now+=60000;
  assert.equal(store.sessionStats(store.get('players',player.id)).durationMs,ended.durationMs);
});
test('stream URL allowlist canonicalizes supported links and rejects unsafe or channel-only YouTube URLs',()=>{
  assert.equal(streamLink('https://twitch.tv/Example?foo=1','twitch').channel,'example');
  assert.equal(streamLink('https://youtu.be/abcdefghijk?t=5','youtube').videoId,'abcdefghijk');
  for(const value of ['javascript:alert(1)','https://twitch.tv.evil.example/user','https://user:pass@twitch.tv/name','https://twitch.tv/directory'])assert.throws(()=>streamLink(value,'twitch'));
  assert.throws(()=>streamLink('https://youtube.com/@runner','youtube'));
});
test('Twitch bot live checks, stale expiry, privacy, and multistream deduplication',async t=>{
  let now=1700000000000;const store=new Store(':memory:',()=>now);t.after(()=>store.close());
  const {player:p}=store.register('Runner');store.streams(p,{twitch:'https://twitch.tv/runner',youtube:'https://youtu.be/abcdefghijk',live:true});
  assert.equal(publicStreams(p,now).twitchStatus,'unknown');
  let live=true;
  const token={request:async url=>{assert.match(url,/user_login=runner/);return new Response(JSON.stringify({data:live?[{user_login:'runner',type:'live'}]:[]}));}};
  await checkTwitchStreams(store,token,'client');
  let updated=store.get('players',p.id);assert.equal(publicStreams(updated,now).twitchStatus,'live');
  const candidates=streamCandidates([{...updated,streams:publicStreams(updated,now)}]);assert.equal(candidates.length,2);
  assert.equal(distinctSlots(candidates,candidates.map(c=>c.key)).filter(Boolean).length,1);
  assert.match(playerUrl(candidates[0],'doctormonty.beer'),/parent=doctormonty.beer/);
  now+=120001;assert.equal(publicStreams(updated,now).twitchStatus,'unknown');
  live=false;await checkTwitchStreams(store,token,'client');updated=store.get('players',p.id);assert.equal(publicStreams(updated,now).twitchStatus,'offline');
  updated.public=false;assert.equal(publicStreams(updated,now),null);
});
test('API protects stream updates, filters category catalog and hides private session statistics',async t=>{
  const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>{app.stop();app.store.close();});
  const base=`http://127.0.0.1:${app.server.address().port}`;
  const catalog=await(await fetch(base+'/api/catalog')).json();assert.deepEqual(catalog.categoriesByMap['ascension'],['Any%']);
  assert.ok(!catalog.categoriesByMap['zetsubou-no-shima'].includes('No Gums'));
  assert.equal((await fetch(base+'/api/me/streams',{method:'POST',body:'{}'})).status,401);
  assert.equal((await fetch(base+'/api/admin/benchmarks',{method:'POST',body:'{}'})).status,401);
  const {player}=app.store.register('Private');app.store.privacy(player,false);
  const view=await(await fetch(base+'/api/players/private')).json();assert.equal(view.session,null);assert.equal(view.streams,null);
  const page=await(await fetch(base)).text();assert.ok(!page.includes('benchmark-form'));assert.ok(!page.includes('legacy companion'));assert.match(page,/Dr Monty Bot/);
});
