// Generated from src/split-rules.js; regenerate with node scripts/generate-split-aliases.mjs.
using System.Collections.Generic;
namespace LiveSplit.ZombiesTracker { public static class SplitAliases {
public static string[] Canonical(string map) { return System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Distinct(System.Linq.Enumerable.Select(System.Linq.Enumerable.Where(Names, p=>p.Key.StartsWith(map+"|")),p=>p.Value))); }
static readonly Dictionary<string,string> Names = new Dictionary<string,string> {
{"shadows-of-evil|rift","Rift"},
{"shadows-of-evil|portal","Rift"},
{"shadows-of-evil|sword","Sword"},
{"shadows-of-evil|flag","Flag"},
{"shadows-of-evil|end","End"},
{"shadows-of-evil|soe egg end","End"},
{"der-eisendrache|bow","Bow"},
{"der-eisendrache|rocket","Rocket"},
{"der-eisendrache|rocket test tp","Rocket"},
{"der-eisendrache|crackle","Crackle"},
{"der-eisendrache|r7","Crackle"},
{"der-eisendrache|r7 end","Crackle"},
{"der-eisendrache|round 7 end","Crackle"},
{"der-eisendrache|round 7","Crackle"},
{"der-eisendrache|tp","TP"},
{"der-eisendrache|teleport 1","TP"},
{"der-eisendrache|back in time","TP"},
{"der-eisendrache|tp 1","TP"},
{"der-eisendrache|first tp","TP"},
{"der-eisendrache|key","Key"},
{"der-eisendrache|keeper start","Key"},
{"der-eisendrache|keeper","Key"},
{"der-eisendrache|key place","Key"},
{"der-eisendrache|boss enter","Boss Enter"},
{"der-eisendrache|boss","Boss Enter"},
{"der-eisendrache|de boss enter","Boss Enter"},
{"der-eisendrache|end","End"},
{"der-eisendrache|de egg end","End"},
{"zetsubou-no-shima|bunker","Bunker"},
{"zetsubou-no-shima|skull","Skull"},
{"zetsubou-no-shima|rainbow round end","Rainbow Round End"},
{"zetsubou-no-shima|kt4 rainbow round end","Rainbow Round End"},
{"zetsubou-no-shima|rainbow","Rainbow Round End"},
{"zetsubou-no-shima|rainbow end","Rainbow Round End"},
{"zetsubou-no-shima|boss enter","Boss Enter"},
{"zetsubou-no-shima|boss","Boss Enter"},
{"zetsubou-no-shima|elevator","Boss Enter"},
{"zetsubou-no-shima|elevator enter","Boss Enter"},
{"zetsubou-no-shima|zns boss enter","Boss Enter"},
{"zetsubou-no-shima|end","End"},
{"zetsubou-no-shima|zns egg end","End"},
{"gorod-krovi|fly 1","Fly 1"},
{"gorod-krovi|first fly","Fly 1"},
{"gorod-krovi|spit","Spit"},
{"gorod-krovi|round end","Spit"},
{"gorod-krovi|round 6","Spit"},
{"gorod-krovi|round 6 end","Spit"},
{"gorod-krovi|spit r6","Spit"},
{"gorod-krovi|r6","Spit"},
{"gorod-krovi|fly 2","Fly 2"},
{"gorod-krovi|second fly","Fly 2"},
{"gorod-krovi|challenges","Challenges"},
{"gorod-krovi|chall start","Challenges"},
{"gorod-krovi|challs","Challenges"},
{"gorod-krovi|challenge start","Challenges"},
{"gorod-krovi|challenges start","Challenges"},
{"gorod-krovi|download","Download"},
{"gorod-krovi|download start","Download"},
{"gorod-krovi|end","End"},
{"gorod-krovi|gk egg end","End"},
{"revelations|keeper","Keeper"},
{"revelations|keeper start","Keeper"},
{"revelations|beast","Beast"},
{"revelations|beast enter","Beast"},
{"revelations|exit","Exit"},
{"revelations|beast exit","Exit"},
{"revelations|squid leave","Exit"},
{"revelations|house","House"},
{"revelations|tp","House"},
{"revelations|teleport","House"},
{"revelations|house enter","House"},
{"revelations|boss 1","Boss 1"},
{"revelations|symbols","Symbols"},
{"revelations|basketball","Basketball"},
{"revelations|boss 2","Boss 2"},
{"revelations|end","End"},
{"revelations|rev egg end","End"},
{"shangri-la|tiles","Tiles"},
{"shangri-la|tiles done","Tiles"},
{"shangri-la|crystal","Crystal"},
{"shangri-la|napalm","Napalm"},
{"shangri-la|radio","Radio"},
{"shangri-la|end","End"},
{"moon|power","Power"},
{"moon|samantha says","Samantha Says"},
{"moon|terminals","Terminals"},
{"moon|hack complete","Terminals"},
{"moon|vril sphere","Vril Sphere"},
{"moon|ball","Vril Sphere"},
{"moon|canister 1","Canister 1"},
{"moon|canister 2","Canister 2"},
{"moon|end","End"},
{"moon|moon egg end","End"},
{"origins|ice staff","Ice Staff"},
{"origins|ice craft","Ice Staff"},
{"origins|fire enter","Fire Enter"},
{"origins|lightning enter","Lightning Enter"},
{"origins|ice leave","Ice Leave"},
{"origins|upgrade","Upgrade"},
{"origins|all upgrade","Upgrade"},
{"origins|wind exit","Upgrade"},
{"origins|end","End"},
{"origins|origins egg end","End"}
};
public static string Known(string map,string name) { string value; return Names.TryGetValue(map+"|"+Detector.Normalize(name),out value)?value:null; }
} }
